version: '2'
services:
    kronos-app:
        image: kronos
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://kronos-postgresql:5432/kronos
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kronos-postgresql:
        extends:
            file: postgresql.yml
            service: kronos-postgresql
